### ISSUE TITLE
Add prefix `cellguide`

### ISSUE THREAD

**Issue by anitacaron** [biopragmatics/bioregistry#1001]
### Prefix

cellguide

### Name

Cell Guide

### Homepage

https://cellxgene.cziscience.com/cellguide

### Source Code Repository

bioregistry

### Description

CellGuide is a comprehensive resource for knowledge about cell types.

### Example Local Unique Identifier

CL_0002623

### Contributor Name

Anita Caron

### Contributor GitHub

anitacaron

### Contributor ORCiD

https://orcid.org/0000-0002-6523-4866

### Additional Comments

The intention is to create cross-reference links in the Cell Ontology to Cell Guide pages.

**Comment by cthoyt** [comment]
Okay, https://github.com/biopragmatics/bioregistry/issues/new?assignees=cthoyt&labels=Provider%2CNew&projects=&template=new-provider.yml&title=Add+provider+for+CL&prefix=cl might be more appropriate issue template to more directly say "cellguide is a place that resolves CL identifiers, like in https://cellxgene.cziscience.com/cellguide/CL_0001061" since `cellguide` is not itself a resource that mints its own identifiers

**Comment by cthoyt** [comment]
@anitacaron here's the solution I have so far:

1. I added cellguide as an alternate provider for CL. This appears on https://bioregistry.io/cl at the bottom like in <img width="954" alt="Screenshot 2023-11-28 at 18 07 55" src="https://github.com/biopragmatics/bioregistry/assets/5069736/240e1746-6daa-4c41-a3d5-cdd8f57568bf">
2. You can use the Bioregistry's provider support in the resolver to write links like https://bioregistry.io/cl:0000062?provider=cellguide

Is this sufficient?

**Comment by anitacaron** [comment]
@dosumis can you comment here, please?

**Comment by dosumis** [comment]
Solution makes sense to me.  My main aim is to have a way to use CURIES to specify links from CL terms to CellGuide - particularly in OLS4 - which I believe uses the bioregistry as a generic way to control resolution from xrefs.  @udp - could you comment on OLS4 use of bioregistry and whether it could support @cthoyt's solution?

**Comment by cthoyt** [comment]
It would be great if we could move this to the OLS tracker, since it's a pretty substantial feature request for them. I think the idea would be that for any ontology that has additional providers in the Bioregistry, that you could have some kind of configuration that tells the OLS to display an additional link on that page for the provider.

I opened a new place for discussion on https://github.com/EBISPOT/ols4/issues/601 and will close this one as complete
