### ISSUE TITLE
Update Resource Description Framework

### ISSUE THREAD

**Issue by cmungall** [biopragmatics/bioregistry#1090]
### Prefix

rdf

### Explanation

- the example curie of [rdf:RDF](https://bioregistry.io/reference/rdf:/RDF) is not a thing
- this should be preferred prefix `rdf` (it may seem this is unneccessary but unfortunately bioregistry inherits the incorrect decision to downcase major database prefixes, so it's necessary to annotate all cases where the preferred prefix is truly downcase as such)

### Contributor ORCID

0000-0002-6601-2165

**Comment by bgyori** [comment]
Hi @cmungall, thanks! How about replacing the example CURE from rdf:RDF to rdf:Property? In terms of the preferred prefix, I think the assumption should be that the default prefix is preferred unless annotated otherwise. Based on https://github.com/linkml/prefixmaps/issues/70, it sounds like there is some code that uppercases prefixes when it shouldn't do that indiscriminately. I suppose adding a preferred lowercase prefix here might fix that.

**Comment by cmungall** [comment]
`rdf:Property` is fine, `rdf:type` is the most widely used.

There is a lot of history on this tracker about casing of prefixes, unfortunately this all stems from a unilateral decision by identifiers.org years ago to downcase everything without asking anyone. We have this resolved at least for the OBO ontologies and we should be seeing no more `go` (though some parts of pyobo still need fixes) but unfortunately for non-OBO databases there is still no way to tell, so it's necessary for downstream code to do uppercase as the default since that is canonical for most bio-databases

**Comment by jamesamcl** [comment]
> the example curie of [rdf:RDF](https://bioregistry.io/reference/rdf:/RDF) is not a thing

I think `rdf:RDF` is actually a thing? e.g. from `mondo.owl` (chosen at random):

```xml
<?xml version="1.0"?>
<rdf:RDF xmlns="http://purl.obolibrary.org/obo/mondo.owl#"
     xml:base="http://purl.obolibrary.org/obo/mondo.owl"
     xmlns:dc="http://purl.org/dc/elements/1.1/"
     ...
```

**Comment by bgyori** [comment]
That's an interesting point, `rdf:RDF` seemed valid to me too until @cmungall made this point. It turns out that it's actually not one of the things defined at https://www.w3.org/1999/02/22-rdf-syntax-ns# and the description at https://www.w3.org/TR/1998/WD-rdf-syntax-19980819/ says "The RDF element is a simple wrapper that marks the boundaries in an XML document between which the content is explicitly intended to be mappable into an RDF data model instance." making it sound like it's just used for wrapping RDF.
