### ISSUE TITLE
Update Online Mendelian Inheritance in Animals

### ISSUE THREAD

**Issue by ImkeTammen** [biopragmatics/bioregistry#1105]
### Prefix

omia

### Explanation

1. Please change the introductory text from: "Online Mendelian Inheritance in Animals (OMIA) is a catalogue/compendium of inherited disorders, other (single-locus) traits, and associated genes and variants in 363 animal species (other than human and mouse and rats and zebrafish, which have their own resources)." to "
"Online Mendelian Inheritance in Animals (OMIA) is a catalogue/compendium of inherited disorders, other (single-locus) traits, and associated genes and variants in more than 500 vertebrate animal species (other than human, mouse, rats, zebrafish and western clawed frog, which have their own resources)." 

2. I noted that the Example Local Unique Identifier is given as ‘1000’ – however OMIA uses the following IDs – either OMIA:xxxxxx or  OMIA:xxxxxx-yyyy.., where xxxxxx is the 6-digit number for a trait/disorder, and yyyy.. is the NCBI species taxonomy id (usually four digits, but sometimes longer). Should the sample ID in the registry be changed accordingly? 
Example URL links and corresponding OMIA IDs are:
https://www.omia.org/OMIA001000/    for     OMIA:001000
https://www.omia.org/OMIA001000/9615/    for     OMIA:001000-9615

3. We have also introduced recently a new ID 'OMIAvariantID:x', where x is a consecutive number starting from 1 and at the moment going up to 1578. These IDs are currently not linked to a public facing URL (URL is only visible to database curators). Can the OMIAvariantID:x be registered with bioregistry or is this only appropriate if the ID can be linked to an URL?

Kind regards,

Imke 

### Contributor ORCID

0000-0002-5520-6597

**Comment by bgyori** [comment]
Hi @ImkeTammen, thanks for the suggestions! I just opened a pull request with some changes.
- I changed the description to the one you provided
- I also updated the ID pattern and the example. For now, the pattern covers IDs consisting of 6 digits. The xxxxxx-yyyy case could also work, though linking to https://www.omia.org/OMIA001000/9615/ is not immediately possible due to having to do string manipulation that goes beyond a simple substitution of the ID into a URL pattern. Would it be possible for the OMIA website to be able to resolve e.g., https://www.omia.org/OMIA001000-9615? If so, we could extend the pattern/resolver to this case.
- As for OMIAvariantID:x, I would suggest submitting a new prefix request (the prefix could be `omiavariant` or `omia.variant`). It is not a problem if the IDs cannot be resolved. The metadata registered on the namespace is still useful.

**Comment by matentzn** [comment]
@ImkeTammen I agree with Ben on

> Would it be possible for the OMIA website to be able to resolve e.g., https://www.omia.org/OMIA001000-9615? If so, we could extend the pattern/resolver to this case.

I would also strongly advocate for this to be possible!

Generally when you design identifiers, it is a good idea nowadays to also think of a simple way to resolve this identifier as is to a URL by just appending it:

```
http://some.url/IDENTIFIER
```

with:

- no need to change the identifier in any way (replacing characters, like `-` to `/`)
- no need to append anything to the identifier (especially not a `/`, so http://some.url/123 should resolve, and there should be no need to do `http://some.url/123/` or even worse, `http://some.url/123.html`.

**Comment by bgyori** [comment]
I think you could still keep the existing URLs working at https://www.omia.org/OMIA001000/9615/ and _in addition_, implement support for resolving URLs using the pattern https://www.omia.org/OMIA001000-9615. This would solve the issue on both sides!

**Comment by bgyori** [comment]
I merged the changes for now, we can come back to the remaining issues in separate PRs.
