### ISSUE TITLE
UniProt: Providers merge the `rdf` and `uniprot` providers please 

### ISSUE THREAD

**Issue by JervenBolleman** [biopragmatics/bioregistry#1130]
Using the http://purl.uniprot.org (not https) as the expected prefix.
The "`rdf`" provider, also provides HTML etc. depending on the http clients desires.

**Comment by bgyori** [comment]
This sounds reasonable to me, i.e., to use http://purl.uniprot.org/uniprot/$1 as the `uri_format` since as far as I can tell, there is no functional difference between what http://www.uniprot.org/uniprot/$1 and http://purl.uniprot.org/uniprot/$1 resolve to in a browser currently. Perhaps the reason they were curated separately is that they behaved differently in the past.
