### ISSUE TITLE
Creative Biolabs - Recombinant Antibodies

### ISSUE THREAD

**Issue by garybrandam** [biopragmatics/bioregistry#1257]
### Prefix

creativebiolabs-net

### Name

Creative Biolabs - Recombinant Antibodies

### Homepage

https://www.creativebiolabs.net

### Source Code Repository

bioregistry

### Description

[Creative Biolabs](https://www.creativebiolabs.net/) is a supplier of a wide range of antibodies from therapeutic antibodies and single domain antibodies to bispecific antibodies and intrabodies.

### Example Local Unique Identifier

TAB-884

### Contributor Name

garybrandam

### Contributor GitHub

garybrandam

### Contributor ORCiD

na

**Comment by nagutm** [comment]
Hi @garybrandam, thank you for your contribution to the Bioregistry.  I have opened a pull request related to Creative Biolabs that you can monitor here: https://github.com/biopragmatics/bioregistry/pull/1260.

I was wondering if you could share some more information about yourself such as you full name, email address and ORCID number if applicable in order to properly credit you with this contribution in the Bioregistry. Thanks!

**Comment by bgyori** [comment]
Added in #1260
