### ISSUE TITLE
Add prefix pav

### ISSUE THREAD

**Issue by matentzn** [biopragmatics/bioregistry#186]
### Prefix

pav

### Name

Provenance, Authoring, and Versioning Vocabulary

### Homepage

https://pav-ontology.github.io/pav/

### Description

PAV is a lightweight ontology for tracking provenance, authorship, and versioning. It specializes the W3C provenance ontology PROV-O in order to describe authorship, curation and digital creation of online resources.

### Example Identifier

authoredBy

### Regular Expression Pattern

[a-z][a-zA-Z]+

### Provider Format URL

https://pav-ontology.github.io/pav/index.html#http://purl.org/pav/$1

### Contributor Name

Nico Matentzoglu

### Contributor ORCiD

0000-0002-7356-1779

**Comment by cthoyt** [comment]
A few notes:

1. I'm not a big fan of redundant prefix usage in the name
2. The example identifier should be a local identifier, so just `authoredBy`. Is the fact that I'm using `identifier` confusing instead of `local identifier`? 
3. The PURL is broken.
4. `https://pav-ontology.github.io/pav/index.html#http://purl.org/pav/$1` should work as a proper format string (though I totally don't agree with this URI in URI nonsense)
5. ORCiD didn't need the whole URI but I guess I should just expect people might do that and go forward accordingly

**Comment by matentzn** [comment]
I though the website is just a website with addition information..

**Comment by matentzn** [comment]
Ok, check again!

**Comment by cthoyt** [comment]
The PR checked your regex and found it wasn't formatted properly (it has to start with ^ and end with $). Updating the issue won't change that now, but I will make the fix directly in the PR and then accept it.
