### ISSUE TITLE
ICDO entry is confusing and has incorrect links to ontologizations of ICD9/10

### ISSUE THREAD

**Issue by cmungall** [biopragmatics/bioregistry#256]
ICDO is the The International Classification of Diseases for On**c**ology

**NOTE** 'O' here stands for Oncology. With a "C". It is not a zero. The O does not stand for ontology. This is not to be confused with ICD9/10/11.

bioregistry has the correct base entry
http://bioregistry.io/registry/icdo

Example query:
http://bioregistry.io/reference/icdo:M9861/3

says "unable to resolve"

However, the page also has links to ontobee, bioportal

The ontobee entry has entries like this:

http://www.ontobee.org/ontology/ICDO?iri=http://purl.obolibrary.org/obo/icdo.owl/ICDO_0000021

there are a few issues with this ontology but the most pertinent one here is **this is not a representation of ICDO**. It is an ontological representation of ICD9 or 10. I filed a ticket here: https://github.com/OntoZoo/ontobee/issues/163

We ontologists love to slap an "O" on the end of database initializations but it's obviously hamrful here

I think this entry should be removed, *possibly* attached to ICD9/10 but I don't think so.

Similarly the bioportal entry is also not ICDO, but another (presumably unsanctioned) ontologization of ICD

https://bioportal.bioontology.org/ontologies/ICDO?p=classes

@graybeal I am not sure what bioportal policy is here, but I don't think this ontology should be squatting the bioportal "ICDO" prefix, this will undoubtedly confuse your users

There are some nuanced issues here about to what degree an ontologization of an existing database should be associated with the primary database entry, but the immediate issue here is that **these are not ICDO**!!!

@mbaudis may be able to help with what the ICDO entries should actually resolve to

**Comment by cmungall** [comment]
Also the canonical form is "ICD-O", all uppercase, with a hyphen. Not sure what the bioregistry policy is on hyphens but this should be an alias at least

**Comment by cmungall** [comment]
FWIW, the wikidata entries resolve to a page that says "Site moved", after which you are redirected to a generic ICD-O page, rather than a link to the actual entry.

**Comment by mbaudis** [comment]
Thanks @cmungall for addressing this. In summary:

* `ICDO`, `ICD-O`, `ICDO3` etc. should stay reserved for implementations of the ICD-O 3 (and future) WHO / IACR cancer codes
* there is AFAIK no working/updated ontology for ICD-O (there is a subset in SNOMED but not always up-to-date)
* Since licensing / re-use for me wasn't fully transparent we went the way of providing a shallow hierarchy for our use (e.g. https://progenetix.org/subsets/biosubsets/?filters=icdom) with "internal pseudo-prefixes" & possible interpolation using our `pgx` prefix, e.g. so [identifiers.org/pgx:icdom-81703](http://identifiers.org/pgx:icdom-81703). 
* I would love if a proper ICD-O ontology could be generated (so probably ICDO3M & ICDO3T prefixed or ICDO3 & M&T id'd through there patterns. Happy to help, weak on formalities ...

##### More:

Regarding what ICD-O should point to: There is AFAIK no hierarchical ontology available for the ICD-O arms, though some shallow approximations exist (since code ranges can be used for grouping) e.g. in NCBI mapping tables and, well, through our progenetix.org. And SNOMED uses (outdated) ICD-O 3 concepts, too, but again - cannot be referenced directly as public codes, AFAIK.

(The peculiarity of ICD-O 3 is the use of the 2 morphology & topography arms for encoding a diagnostic concept; e.g. "Adenocarcinoma, NOS" `8140/3` of the "stomach" `C16.9`, versus "Adenocarcinoma, NOS" `8140/3` of the "Rectum, NOS" `C20.9`. But I digress...)

* [WHO ICD-O info page](https://www.who.int/standards/classifications/other-classifications/international-classification-of-diseases-for-oncology)
* [WHO code list downloads](https://apps.who.int/classifications/apps/icd/ClassificationDownload/DLArea/Download.aspx)
* shallow hierarchy we use on Progenetix for [ICD-O 3 morphologies](https://github.com/progenetix/bycon/blob/master/byconeer/rsrc/icdom/numbered-hierarchies.tsv) and  [ICD-O 3 topographies](https://github.com/progenetix/bycon/blob/master/byconeer/rsrc/icdot/numbered-hierarchies.tsv) - column 3 is the depth; codes are modified & pseudo-prefixed (e.g. `s/^(\d{4})\/(\d)$/icdom-$1$2/`)
* [SEER ICD-O-3 coding guidelines](https://seer.cancer.gov/icd-o-3/) - where codes may diverge from WHO over time

**Comment by cmungall** [comment]
@mbaudis 

agree with all comments, thanks

re
> there is AFAIK no working/updated ontology for ICD-O (there is a subset in SNOMED but not always up-to-date)
> I would love if a proper ICD-O ontology could be generated (so probably ICDO3M & ICDO3T prefixed or ICDO3 & M&T id'd through there patterns. Happy to help, weak on formalities ...

You may want to look at Oliver's response:

https://github.com/OntoZoo/ontobee/issues/163#issuecomment-983291880

Oliver seems to be in contact with the developer of this particular ontologization of ICD-O, I don't know if this satisfies your desiderata for a "proper" ICD-O ontology, but we should probably carry on the discussion there

In terms of action items for bioregistry, I think we should follow @mbaudis' advice:

> ICDO, ICD-O, ICDO3 etc. should stay reserved for implementations of the ICD-O 3 (and future) WHO / IACR cancer codes

It's fine for these to stay non-resolvable for now

And I *don't* think we need an entry for the existing problematic ontologization of ICD-9/10/11 that is on ontobee - any more than we need to an an entry for every bioportal ontology (if we do start doing this we need to really start thinking carefully about avoiding namespace squatting)

**Comment by mbaudis** [comment]
+1

    It's fine for these to stay non-resolvable for now


`¯\_(ツ)_/¯ `

**Comment by cthoyt** [comment]
- The ICDO issues were fixed in #325.
- I'm not sure still about where `ICDO3` should go (as a prefix for `ICDO` or as a new prefix?)
- Not sure how I feel about having dashes in a preferred prefix. I'm going to lean towards not allowing that for now
- Bioregistry will _never_ auto-import Bioportal - there is way too much garbage there

I don't think there are any other action items, so I will close this. Thanks for the nice discussion
