### ISSUE TITLE
How to deal with BioPortal?

### ISSUE THREAD

**Issue by matentzn** [biopragmatics/bioregistry#273]
In a recent issue on OBO: https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1703

a ontology provider noticed  that they had just registered a prefix with OBO that conflicts with BioPortal. I would like to avoid such things in the future - does bioregistry cover or plan to cover bioportal prefixes?

**Comment by cthoyt** [comment]
In the section [_Why does the Bioregistry not completely cover some resources?_](https://bioregistry.io/summary#why-does-the-bioregistry-not-completely-cover-some-resources) on the About page of the Bioregistry site, it's briefly mentioned that the BioPortal is not automatically added to the Bioregistry the way that MIRIAM and OBO Foundry are because BioPortal has an incredible amount of low-quality content. I see a two major problems with adding BioPortal entries:

1. It would create a huge amount of collisions since people who submit the BioPortal often aren't aware of high quality resources themselves
2. It would import many low-quality resources, which is antithetical to the philosophy of the Bioregistry to be high quality. If there are people who have an ontology in BioPortal that they believe is high quality, anyone is free to [request a new prefix](https://github.com/biopragmatics/bioregistry/issues/new/choose) through the linked issue template chooser

That being said, the Bioregistry does automatically align to BioPortal for already existing entries in the Bioregistry, so there are quite a few out-links.

Expand this to see the coverage report - you'll see that more than half of the BioPortal is not covered by the Bioregistry.

<details>

[![Bioregistry coverage summary](https://raw.githubusercontent.com/biopragmatics/bioregistry/main/docs/img/bioregistry_coverage.svg)](https://bioregistry.io/summary)
</details>

**Comment by cthoyt** [comment]
The conflicts that I've curated manually are all in this file https://github.com/biopragmatics/bioregistry/blob/main/src/bioregistry/data/mismatch.json

The curation sheet for BioPortal (which represents all unaligned prefixes) is https://github.com/biopragmatics/bioregistry/blob/main/src/bioregistry/data/external/bioportal/curation.tsv. Because the BioPortal API does not let you get direct access to most of the metadata for each entry, unfortunately the only thing that's represented in this sheet is the BioPortal prefix and BioPortal name. This makes it awfully tricky/time-consuming to do untargeted curation

**Comment by matentzn** [comment]
super useful, thanks.

**Comment by cthoyt** [comment]
I’m going to close this issue. Feel free to Re-open if there’s an associated action item
