### ISSUE TITLE
doi and linked data URLs - dx vs non-dx

### ISSUE THREAD

**Issue by cmungall** [biopragmatics/bioregistry#287]
http://bioregistry.io/registry/doi

will map a CURIE `doi:10.1038/nbt1156` to 
http://doi.org/10.1038/nbt1156 

which is perfectly fine for humans (although it should be https, that is not my concern here)

what URI should be used in a linked data context?

Let's ask doi:

```turtle
✗  curl -s -LH "Accept: text/n-triples" http://doi.org/10.1038/nbt1156  | grep sameAs
<http://dx.doi.org/10.1038/nbt1156> <http://www.w3.org/2002/07/owl#sameAs> <info:doi/10.1038/nbt1156> .
<http://dx.doi.org/10.1038/nbt1156> <http://www.w3.org/2002/07/owl#sameAs> <doi:10.1038/nbt1156> .
<http://id.crossref.org/issn/1087-0156> <http://www.w3.org/2002/07/owl#sameAs> "urn:issn:1087-0156" .
<http://id.crossref.org/issn/1087-0156> <http://www.w3.org/2002/07/owl#sameAs> "urn:issn:1546-1696" .
```

They are explicitly declaring a clique of 3 equivalent URIs. However, none of them are `//doi.org`, two an URNs, and the only URL is `http://dx.doi.org/` based

This yields nothing:

```bash
curl -s -LH "Accept: text/n-triples" http://doi.org/10.1038/nbt1156  | grep //doi.org
```

I believe dx is widely regarded as supported but not preferred. However, this is in contrast to the triples provided.

I found this factsheet
https://www.doi.org/factsheets/DOI_PURL.html

But it seems to be an out-of-context argument against using the purl.org server?

Ideally bioregistry could be a clearinghouse for what the best linked data identifier to use is for a resource like DOIs. It seems we have centered on the non-dx form for most OBO ontologies. Which is in line with conventional wisdom. But it's troubling that this is not the same as the semantic web IDs produced by the crossref system itself.

Maybe there is no action here, and it is what it is

**Comment by cthoyt** [comment]
I’d be happy to accept a suggestion to change the URI format string. However, solving the problem of “what’s the canonical URI for an entity” is not a high priority of the bioregistry - what we can do instead is track that there are several potential valid URIs that can be created from a given CURIE. I’ll send a PR to demonstrate using the suggestions you made

**Comment by dhimmel** [comment]
Copying this comment by @cmungall from https://github.com/biopragmatics/bioregistry/pull/288#issuecomment-1036334576:

> I guess as sort of a linked data person and the originator of the ticket I would say just go with the canonical one [like `https://doi.org/$1`]. It’s what we use in all our owl anyway… my point with the original ticket was to highlight the big difference between what doi were saying with one half of their stack and the other and maybe even start a dialog with them to get their triples changed

Sounds like an upstream issue that the `text/n-triples` needs to be updated to include the more recent and now standard resolution URL in `sameAs`. We could reach out to `contact@doi.org`, but since the request is using content negotiation, I think it actually is being delegated to the respective Registration Agency. For example, if I try a DOI registered with DataCite, the response looks different:

```sh
curl -s -LH "Accept: text/n-triples" https://doi.org/10.6084/m9.figshare.3761562.v2127  | grep sameAs
```

I only see one `sameAs`:

```
"sameAs":"https://figshare.com/articles/dataset/Online_Labour_Index_Measuring_the_Online_Gig_Economy_for_Policy_and_Research/3761562/2127"
```

So perhaps we should notify DataCite and Crossref so they can agree on the same `sameAs` clauses. @cmungall in the ideal world, what should those clauses be? Is it important to list all possible URLs or just the primary?
