### ISSUE TITLE
Provide purls for published contexts?

### ISSUE THREAD

**Issue by matentzn** [biopragmatics/bioregistry#317]
One of my builds just broke because it dependent on obo_synonyms.context.jsonld and it recently changed locations. Maybe w3id.org?

Old link: https://raw.githubusercontent.com/bioregistry/bioregistry/main/docs/_data/contexts/obo_synonyms.context.json
New Link: https://github.com/biopragmatics/bioregistry/raw/main/exports/contexts/obo_synonyms.context.jsonld

**Comment by cthoyt** [comment]
Strange, I don't think they have moved. Either way, this seems like a nice idea. I've labeled it as "manuscript" and "good first issue" since I think anyone can set this up for us, then potentially write a paragraph about why you'd want to refer to resources this way to go in the manuscript (and then be a co-author)

@matentzn I already have a job for you and @hrshdhgd to write a paragraph on SSSOM to go in the paper so you don't necessarily have to be responsible for this, but if you want to get someone more junior to learn about this in a practical setting then feel free to recommend someone to take care of this

**Comment by matentzn** [comment]
> Strange, I don't think they have moved.

Used to be here:
https://raw.githubusercontent.com/bioregistry/bioregistry/main/docs/_data/contexts/obo_synonyms.context.json

> if you want to get someone more junior to learn about this in a practical setting then feel free to recommend someone to take care of this

We can take care of this - I have done it many times and it will take a few seconds, but it kinda is your resource; if you want I can create the PR for you, then you should own it though :P 

Anything you need @cthoyt, as long as we know plenty of time in advance - just add it as an issue on sssom-py and we will pencil it in.

**Comment by cthoyt** [comment]
You're right, they did move, but this was long time ago and I forgot 😅  (sorry). I will think about how I want to proceed (and let you into the google doc for the bioregistry paper ASAP)

**Comment by cthoyt** [comment]
See https://github.com/biopragmatics/bioregistry/tree/main/exports/contexts

This was fixed in #1080
