### ISSUE TITLE
Use case: maintaining a prescriptive context

### ISSUE THREAD

**Issue by matentzn** [biopragmatics/bioregistry#324]
I want to be sure while I am promoting bioregistry around that the following use case can be captured. 

We should be able to:

- [ ] define a _project specific context_, i.e. obo context
- [ ] associate some orcids with that context that declare us as the _maintainers_
- [ ] have some kind of _default order for which prefix sources_ (prefix commons, OBO etc) we want to prefer, and the rest being suggested as "defaults" by bioregistry
- [ ] _define the preferred prefixes for each URI expansion_ (example: we want to use `DOI:` for dois, not `doi:`)
- [ ] _define the preferred URI expansions for each prefix_ (example: we want to expand `DOI:` to "https://doi.org/", not any other URL)
- [ ] we need a mechanism to _fix preferred prefixes_ for each URI expansion (i.e. when we say: "preferred" somewhere and no matter what happens, we need to be able to rely on the fact that this preferred prefix cannot be changed without the explicit agreement of the maintainers documented above.
- [ ] we need a mechanism to _fix the preferred URI expansions_ for each prefix (i.e. we say: "preferred" somewhere and no matter what happens, we need to be able to rely on the fact that this preferred prefix cannot be changed without the explicit agreement of the maintainers documented above.

Can we confirm whether this extensive set of requirements can be met by bioregistry or not? Thanks :)

cc @dosumis @cmungall 

cf. https://obo-communitygroup.slack.com/archives/C01R2D66249/p1645718367637119

**Comment by cthoyt** [comment]
I'm still having a hard time wrapping myself around the ideas here.

Should this kind of thing even be in the Bioregistry? I'm very worried to have parts of the Bioregistry that should _only_ be edited by a certain set of people. Will these people get onboarded to the Bioregistry review team? Then what happens if they're not responsive? Consider the various fiefdoms within the OBO Foundry project that have this issue.

Should I personally spend time supporting the development of this kind of thing? How much bloat should I allow into the Bioregistry to support people from a specific community?

Can we even plan for the Bioregistry to be _prescriptive_ without massive prior buy-in? I don't want to commit to something that can't be enforce, either (consider the issues with enforcing OBO standards).

All that being said, I'm sure it would be possible to build something like this with the Bioregistry. The following code is what produces the OBO-context prefix maps:

https://github.com/biopragmatics/bioregistry/blob/6a978c441025c3eb97f8341a1a2eca56cb01081e/src/bioregistry/export/prefix_maps.py#L110-L124

<details>
<summary>This could be generalized to be stored in an external configuration file like this</summary>

```json
{
  "obo": {
    "name": "Open Biomedical Ontologies Context",
    "description": "The OBO Context exists for the following reasons: ...",
    "maintainers": {
      "github": "matentzn",
      "name": "Nico Matentzoglu",
      "orcid": "0000-0002-7356-1779"
    },
    "priority": [
      "obofoundry",
      "default",
      "prefixcommons",
      "miriam",
      "ols"
    ],
    "use_preferred": true,
    "prefix_remapping": {
      "umls": "UMLS",
      "snomedct": "SCTID",
      "ensembl": "ENSEMBL",
      "doi": "DOI"
    },
    "custom_prefix_map": {
      "DOI": "https://doi.org"
    }
  }
}
```

</details>

That might already constitute 95% of what you want

**Comment by matentzn** [comment]
Lets have a quick catch up call when you have time and discuss how to move forward. Your suggestion sounds good, but I would like to talk it over - in case I am accidentally stretching the point of bioregistry here.
