### ISSUE TITLE
Add new collection: FHIR Code Systems

### ISSUE THREAD

**Issue by cmungall** [biopragmatics/bioregistry#346]
## Title

FHIR Code Systems

## Description

The CodeSystem resource is used to declare the existence of and describe a code system or code system supplement and its key properties, and optionally define a part or all of its content.

taken from https://build.fhir.org/codesystem-definitions.html

## Prefixes

todo

## Author Name

todo

## Author ORCID Identifier

this should not be me

cc @gaurav

I might hold off until this issue is resolved:

https://github.com/w3c/hcls-fhir-rdf/issues/94

as the fhir-rdf group are working on strategies to provide stem URIs for all fhir code systems

**Comment by cthoyt** [comment]
@cmungall @gaurav is there any movement forwards on this? I'm worried to have lots of stale issues piling up, so if nobody has a chance to respond to this by the end of the week, I'll close it.

**Comment by gaurav** [comment]
I think it's okay to close this for now -- our proposal to HL7 asking them to add RDF prefixes to FHIR CodeSystem/NamingSystem entries is still being worked on, and the proposal may need to be modified if they don't like it as proposed. So I think we're some time away from having an explicit list of prefixes defined in that group. Is that right @cmungall? Once we know what HL7 would be willing to accept, we can reopen this proposal if needed.

Note that his collection will likely never be "complete", since we hope that the HL7 UTG will continue adding prefixes to FHIR CodeSystem/NamingSystems after we create our initial set of prefixes. However, we could build a tool to keep the list of prefixes defined in the FHIR CodeSystem/NamingSystem registry in sync with Bioregistry.io, so this will hopefully become useful at some point in the future.

**Comment by cthoyt** [comment]
I'd be happy to re-open when someone is able to provide some more context/make some forwards motion. Keep in mind that not everyone is aware of what FHIR is and the website is pretty hard to figure out, so let's do our best to make this accessible for anyone who wants to understand if we do a Round 2
