### ISSUE TITLE
Is there a reason why `curie_from_iri` returns a normalized prefix rather than the preferred prefix?

### ISSUE THREAD

**Issue by hrshdhgd** [biopragmatics/bioregistry#482]
When I run the following:

```python
from bioregistry import curie_from_iri

curie_from_iri("http://purl.obolibrary.org/obo/GO_9999999")
```
gives me `go:9999999` but I want `GO:9999999` which would be a CURIE with a 'preferred prefix'. As of now I have massaged the data to get it as follows:

```python
from bioregistry import parse_iri, get_preferred_prefix, curie_to_str

prefix, identifier = parse_iri("http://purl.obolibrary.org/obo/GO_9999999")
preferred_prefix = get_preferred_prefix(prefix)
curie = curie_to_str(preferred_prefix, identifier)
```

Questions:

1.  Is there a reason why the preferred prefix isn't the default result of `parse_iri`
2. Is there a more elegant way of doing this?
3. If I provide a prefix map, it still gives me the normalized prefix. Although I'm not sure how that would help either. Example below:
```python
from bioregistry import curie_from_iri

curie_from_iri(
    "http://purl.obolibrary.org/obo/GO_9999999", 
    prefix_map={"GO": "http://purl.obolibrary.org/obo/GO_"},
)
```

cc: @matentzn @sierra-moxon (fyi)

**Comment by cthoyt** [comment]
> 1. Is there a reason why the preferred prefix isn't the default result of parse_iri

The preferred prefix field in the Bioregistry lets people write how they should be stylized (mostly relevant if you're part of the OBO cabal). The Bioregistry has an internal standard for each prefix based on normalization/canonicalization, so it outputs these. It also has extensive tools for mapping Bioregistry prefixes to domain/context-specific prefixes, such as for the OBO community, to enable you to map parsed canonical prefixes/CURIEs how you want.

> 2. Is there a more elegant way of doing this?

No, but I'd be willing to review a PR to provide this shortcut

> If I provide a prefix map, it still gives me the normalized prefix. Although I'm not sure how that would help either.

This might be an artifact of how the prefix map processing works since this will overlap with the default prefix `go`

https://github.com/biopragmatics/bioregistry/blob/2c1727154d812e4853cbf8bfef6006da0aa17bb8/src/bioregistry/resource_manager.py#L921-L935

There might actually be an unrelated bug here now that I'm looking at it that introduces duplicates / incorrect ordering

**Comment by hrshdhgd** [comment]
PR: https://github.com/biopragmatics/bioregistry/pull/484
