### ISSUE TITLE
Add prefix ICD10WHO

### ISSUE THREAD

**Issue by joeflack4** [biopragmatics/bioregistry#485]
### Prefix

ICD10WHO

### Name

World Health Organization

### Homepage

https://icd.who.int/browse10/2019/en#/

### Description

ICD10 is well known. There exists a WHO version, which is essentially a base version from which other versions are derived. However, ICD10 is often mistaken to mean ICD10CM. Thus, to avoid ambiguity, we propose ICD10WHO as a community driven prefix.

### Example Local Unique Identifier

C34

### URI Format String

https://icd.who.int/browse10/2019/en#/$1

### Contributor Name

Joe Flack

### Contributor GitHub

joeflack4

### Contributor ORCiD

0000-0002-2906-7319

### Additional Comments

See discussion: https://github.com/biopragmatics/bioregistry/issues/251

**Comment by cthoyt** [comment]
@joeflack4 we'll need a few things to move forwards:

1. Additional example local unique identifies to get a better feel of what's in this semantic space
2. Regular expression for *all* terms in this semantic space
3. An updated description - this should be for people who don't know what ICD10WHO is. This should _not_ be a justification of project-specific usage, but rather text to let people who aren't familiar with this resource to understand what it is. Ideally, this also includes a description of how it's different from ICD10 and ICD10CM, and when it's appropriate to use it instead

**Comment by cthoyt** [comment]
@matentzn so the other option was to rename the existing `icd10` to `icd10who` -> is that an alternative?

**Comment by matentzn** [comment]
I think `icd10` is like `dc` - you cant tell every what it refers to. Is it possible to add `icd10`, and `ICD10`, as deprecated prefixes to both icd10cm and icd10who? Since it can be both, we should discourage using it altogether.

**Comment by matentzn** [comment]
> 1. Additional example local unique identifies to get a better feel of what's in this semantic space

So many different things..:

Examples of grouping classes in ICD10WHO:
- [V20-V29](https://icd.who.int/browse10/2019/en#/V20-V29) Motorcycle rider injured in transport accident
- [G00-G09](https://icd.who.int/browse10/2019/en#/G00-G09) Inflammatory diseases of the central nervous system

Examples of leaf codes:

- V22: Motorcycle rider injured in collision with two- or three-wheeled motor vehicle
- D01: Carcinoma in situ of other and unspecified digestive organs

> 2. Regular expression for all terms in this semantic space

There are many different regexes that could apply (the issue seems to be quite contentious after googling a few minutes), depending on how much specificity you want for the codes: https://medium.com/@manabu.torii/regex-pattern-for-icd-10-cm-codes-5763bd66e26d. Maybe start with `([A-TV-Z][0-9][A-Z0-9](\.?[A-Z0-9]{0,4})?)`

> An updated description

Adapted from Wikipedia:

`ICD-10 is the 10th revision of the International Statistical Classification of Diseases and Related Health Problems (ICD), a medical classification list by the World Health Organization (WHO). While WHO manages and publishes a base version of the ICD, several member states have modified it to better suit their needs, effectively generating derived alternative classifications such as the ICD10-CM. In the base classification (ICD10WHO), the code set allows for more than 14,000 different codes, covering areas from diseases and injuries to complications during surgery.`

**Comment by joeflack4** [comment]
Thanks for handling this for me @matentzn !

**Comment by cthoyt** [comment]
So I think the main thing I've learned from this conversation is that ICD10 and ICD10WHO are used interchangeably to refer to the same semantic space. Therefore, we should start by adding `ICD10WHO` as a synonym to `ICD10` then continue discussion about which one should be the Bioregistry's *canonical* prefix

**Comment by matentzn** [comment]
I would say, though, that ICD10 is used more frequently as a synonym for ICD10CM than ICD10WHO. In practice both happen, often.

**Comment by cthoyt** [comment]
Historically, the other registries have associated ICD10 with ICD10WHO (e.g., identifiers.org and Wikidata) so since there's doubt maybe being consistent with them is the best for now

**Comment by matentzn** [comment]
Yes, no doubt! If we have to add ICD10 as a synonym, is should the to WHO

**Comment by cthoyt** [comment]
Closed in favor of #523
