### ISSUE TITLE
uniprot metaregistry links are broken

### ISSUE THREAD

**Issue by cmungall** [biopragmatics/bioregistry#628]
For example:

https://bioregistry.io/registry/drugcentral

In

Registry Name | Metaprefix | External Prefix
-- | -- | --
Biolink Model Registry | biolink | DrugCentral
FAIRSharing | fairsharing | FAIRsharing.3me82d
UniProt Cross-ref database | uniprot | DrugCentral

Links to 
https://www.uniprot.org/database/DB-DrugCentral

The actual link is:

https://www.uniprot.org/database/DB-0239

This bug seems to hold for all uniprot metaregistry entries. I am wondering if this is a recent uniprot change?

Additionally, bioregistry itself should probably have an entry like `uniprot.db` that links to this

**Comment by cmungall** [comment]
FWIW it should be easy to get the mappings from the sparql endpoint, e.g

https://sparql.uniprot.org/sparql/?query=SELECT+%3Fp+%3Fo+WHERE+%7B%3Chttp%3A%2F%2Fpurl.uniprot.org%2Fdatabase%2FDrugCentral%3E+%3Fp+%3Fo%7D%0D%0A&format=html&query=SELECT+%3Fp+%3Fo+WHERE+%7B%3Chttp%3A%2F%2Fpurl.uniprot.org%2Fdatabase%2FDrugCentral%3E+%3Fp+%3Fo%7D%0D%0A

**Comment by bgyori** [comment]
Thanks @cmungall! The current implementation uses https://rest.uniprot.org/database/stream?format=rdf&query=* to get the data and it seems to successfully retrieve all the relevant info. Looking at bioregistry.json, the `drugcentral` block contains the following mapping:
```
    "uniprot": {
      "category": "Chemistry databases",
      "identifier": "239",
      "link_is_explicit": "true",
      "name": "DrugCentral",
      "prefix": "DrugCentral",
      "uri_format": "https://drugcentral.org/target/$1"
    },
```
Given that the correct `identifier` appears in this block, I suspect this is mainly an issue with the website, not the underlying data. Namely, the website appears to attach the `prefix` to the URL pattern https://www.uniprot.org/database/DB- instead of the `identifier`.

It is interesting to note that an alternative resolver for this entry - resolving to a different but also relevant page - would be http://purl.uniprot.org/database/DrugCentral which uses the `prefix` (i.e., DrugCentral), not the `identifier`.

**Comment by bgyori** [comment]
Looks like the links are always generated using the prefix appearing in the mappings to external resources, which for `drugcentral` are:
```
    "mappings": {
      "biolink": "DrugCentral",
      "fairsharing": "FAIRsharing.3me82d",
      "uniprot": "DrugCentral"
    },
```

**Comment by cthoyt** [comment]
Maybe this happened because they changed the format of the file that Bioregistry parses along with their other recent API-breaking updates - I don't think this was incorrect before.

Bioregistry actually already has an entry for uniprot databases https://bioregistry.io/registry/uniprot.resource that the metaregistry entry is linked to, but this isn't explicit from the site. I will add that.

**Comment by cthoyt** [comment]
Thanks @cmungall and @bgyori for checking this out. I just made an update in #629 that modernizes the code to use the new data format (it even has JSON instead of XML now!). I also added a unit test to make sure that the prefiexs in mappings match the associated regular expression patterns.
