### ISSUE TITLE
ECO entry, under "prefixcommons", contains wrong value in the "synonyms" section

### ISSUE THREAD

**Issue by IgorRodchenkov** [biopragmatics/bioregistry#776]
For "eco", in the "prefixcommons", currently there in bioregistry.json it's like:
```
      "synonyms": [
        "evidence codes ontologyobo.eco"
      ],
```
but should be - 
```
      "synonyms": [
        "evidence codes ontology",
        "obo.eco"
      ],

```

**Comment by cthoyt** [comment]
Hi @IgorRodchenkov, the data from Prefix Commons (now called the Bio2KG Registry) is only imported by the Bioregistry and is not itself maintained here.

The data itself is imported from the google sheet at http://tinyurl.com/lsregistry, so I made a comment on the google sheet corresponding to your suggestion.

Note that the Bioregistry doesn't currently import the synonyms from this resource in full, since there are some conflicts with synonyms in the Bioregistry. I will look into resolving those mismatches then assess the added benefit of these synonyms.

**Comment by cthoyt** [comment]
I've improved the importer from prefix commons to remove some questionable synonyms, so this specific issue is now solved.

**Comment by micheldumontier** [comment]
i fixed the lack of comma for the eco synonyms in the lsr spreadsheet.
