### ISSUE TITLE
preferred prefix is not respected on bioregistry pages

### ISSUE THREAD

**Issue by cmungall** [biopragmatics/bioregistry#871]
https://bioregistry.io/registry/go

has:

Example CURIE
[go:0032571](https://bioregistry.io/reference/go:0032571)

But this is not a valid CURIE for GO. It's not even an alternative, it's expressly wrong.

Also this text is confusing:

_The legacy MIRIAM standard for generating CURIEs with this resource annotates the namespaceEmbeddedInLUI as true. This means that you may see local unique identifiers that include a redundant prefix and delimiter (also known as a banana) and therefore look like a CURIE. For Gene Ontology, the banana looks like GO:. Therefore, you may see local unique identifiers for this resource that look like GO:0032571 (instead of the canonical form 0032571) and CURIEs for this resource that look like go:GO:0032571 (instead of the canonical form go:0032571). The Bioregistry will automatically strip off the banana when standardizing local unique identifiers and CURIEs._

I don't know what "banana looks like GO:. " means. and of course "instead of the canonical form go:0032571" is not correct

Edit: the part about the text about bananas got its own issue in https://github.com/biopragmatics/bioregistry/issues/908

**Comment by cthoyt** [comment]
I addressed the preferred prefix part in #877. I've tried several times to write a succinct, coherent explanation of what's going on with the bananas. It hasn't been easy. The short version is that Identifiers.org has very misguided regular expression describing the local unique identifiers for many semantic spaces (most, but not all are OBO Foundry ontologies).

E.g., the regular expression in Identifiers.org for local unique identifiers in GO is `^GO:\d{7}$`. This doesn't make sense since it means if you make a CURIE, which is prefix + colon + local unique identifier, you'll get something like `GO:GO:1234567`. This is definitely bad. Therefore, the banana is a field in the Bioregistry that helps better contextualize these choices. In the GO entry, the redundant bit inside the Identifiers.org regex is `GO:`, therefore this is what's stored in the banana field.

An alternate example is for SIO. The Identifiers.org regex is `^SIO_\d{6,6}$`. Therefore, `SIO_` is the banana.

I will think more about how to improve the explanation in the web page and make an update soon
