### ISSUE TITLE
Add prefix HL7 

### ISSUE THREAD

**Issue by lnanderson** [biopragmatics/bioregistry#886]
### Prefix

HL7

### Name

Health Level Seven Reference Implementation Model, Version 3

### Homepage

https://bioportal.bioontology.org/ontologies/HL7

### Repository

https://bioportal.bioontology.org/

### Description

This version is the first update to Normative RIM, Release 3. It is based on changes approved in Harmonization in November 2010. This release of the RIM is bound to HL7 Abstract Data Types Release 2.

### License

unknown

### Example Local Unique Identifier

C1553741

### URI Format String

http://purl.bioontology.org/ontology/HL7/C1553741

### Contributor Name

Lindsey N Anderson

### Contributor GitHub

lnanderson

### Contributor ORCiD

0000-0002-8741-7823

### Contact Name

Methodology and Modelling Committee

### Contact ORCiD

unknown

### Contact GitHub

unknown

### Contact Email

mnm@lists.hl7.org

### Additional Comments

I believe this ontology description references the UMLS [HL7V3.0 (HL7 Version 3.0) - Synopsis](https://www.nlm.nih.gov/research/umls/sourcereleasedocs/current/HL7V3.0/index.html) page, under   "Sited Consulted" reference link for [HL7-supported Code Systems Index](https://www.hl7.org/v3ballotarchive/v3ballot/html/infrastructure/vocabulary/vocabulary.html#voc-systems). Very unclear which authors submitted this collection to Bioportal, but would be a nice compliment to Bioregistry sources [hl7.v2codesystem](https://bioregistry.io/registry/hl7.v2codesystem) & [hl7.v3codesystem](https://bioregistry.io/registry/hl7.v3codesystem) if applicable. Code system is included in term label references, see example for "[AcknowledgementCondition [2.16.840.1.113883.5.1050]](https://terminology.hl7.org/5.1.0/CodeSystem-v3-AcknowledgementCondition.html)" as above included Example Local Unique Identifier. 

Contacts may relate to this working group homepage on Confluence: [Methodology and Modelling Committee](https://confluence.hl7.org/display/MnM/Modeling+and+Methodology). 

Note: I was unclear if this needed to reference this Bioregistry metaregistry page: [hl7](https://bioregistry.io/metaregistry/hl7)

**Comment by cthoyt** [comment]
This request doesn't make sense for the Bioregistry - this ontology is reusing UMLS for its identifiers. Since the Bioregistry is keeping track of semantic spaces, this entry is out of scope. Keep in mind that most ontologies also have a semantic space that matches 1-1, but this isn't always the case (such as here).

Further, you can see the [HL7 metaregistry entry](https://bioregistry.io/metaregistry/hl7) in the Bioregistry is actually piggybacked as part of the OID system. I am not a big fan of the information organization from this group...

@lnanderson overall my advice is be much much more careful about the content you get from BioPortal. You probably realized most of it is totally messy, undocumented, and/or low quality.
