### ISSUE TITLE
The url that resolves the hpath ontology 

### ISSUE THREAD

**Issue by ltrainstg** [biopragmatics/bioregistry#927]
### Prefix

MC

### Explanation

# Problem
The resource in question is the hpath ontology listed here: https://bioregistry.io/registry/hpath

The example case does not resolve to the correct resource, and that probably means none of the resource links do. 
E.G. http://purl.obolibrary.org/obo/MC_2000191 links to http://ontologies.berkeleybop.org/. 
The resource it does link to is 'http://ontologies.berkeleybop.org/' which doesn't seem to have anything to do with hpath. 

## Proposed fix
It should probably just resolve to the raw source file for all link of form http://purl.obolibrary.org/obo/***
The raw source is just a smaller file of ~1000 terms. See: https://raw.githubusercontent.com/Novartis/hpath/master/src/hpath.obo. 

## Misc
Thanks for creating this registry. I think this is the appropriate place for the ticket, but not sure. 
I think it's under **UPDATE** since I think the link just needs to be changed. 

### Contributor ORCID

0000-0003-0296-4949

**Comment by matentzn** [comment]
The problem here is that:

1. hpath is using obo format, which is by default interpreted using OBO purls
2. hpath is not in OBO foundry, so PURLs don't resolve

There is an effort underway by @balhoff to get prefixes into OBO format, so that hpath could simply decide to use a different URI scheme. They should not the using the OBO foundry one

In the meantime, maybe redirect to something like Bioportal

**Comment by cthoyt** [comment]
I would love to see headway on this work @balhoff! This will be super useful for anyone who wants to generate OBO content like in https://github.com/biopragmatics/obo-db-ingest.

@ltrainstg you can see that there are actually many ontologies listed in the Bioregistry that have a similar issue. I wrote a blog post about it in https://cthoyt.com/2023/03/11/obolibrary-masquerade.html. I think therefore this issue is out of scope for the Bioregistry.

However, one thing we could do is create some auto-generated pages for entries on HPATH in this repo https://github.com/biopragmatics/providers where I have done similar things for other ontologies. The last bit that's a problem though is that we probably can't register a redirect in the OBO PURL system for this since it's not active nor trying to be an OBO foundry ontology

**Comment by cthoyt** [comment]
So here are the solutions I can provide:

1. in #993 I fixed the way the ontology download link is annotated to be correctly categorized as OBO and not OWL. I also added notes describing the situation of HPATH
2. You can look in https://github.com/OBOFoundry/purl.obolibrary.org to adjust how the OBO PURL system works. I'm not sure what the rules are for adding non-obo ontologies there. You can either post an issue directly on that tracker, or maybe ask a question on https://github.com/OBOFoundry/OBOFoundry.github.io.

Overall, the Bioregistry's job is to keep record of which URI formats are used for entities in a resource. Some URIs are created by accident, like the ones for HPATH. In a second pass, I might be able to more carefully which URIs are meant to be URLs and suggest not resolving them from the Bioregistry page. I hope this is an okay compromise in the mean time :)
